# Example: Using secretKeyRef for sensitive values in Langfuse Helm Chart
# This file demonstrates how to use the new `secretKeyRef` feature to source
# connection details from Kubernetes secrets for PostgreSQL and Redis.

apiVersion: v1
kind: Secret
metadata:
  name: langfuse-db-secrets
  namespace: default
type: Opaque
data:
  # Base64 encoded values for PostgreSQL
  POSTGRES_HOST: "cG9zdGdyZXMtaG9zdC5leGFtcGxlLmNvbQ==" # postgres-host.example.com
  POSTGRES_PORT: "NTQzMg==" # 5432
  POSTGRES_USER: "bGFuZ2Z1c2VfdXNlcg==" # langfuse_user
  POSTGRES_DB: "bGFuZ2Z1c2VfZGI=" # langfuse_db

---
apiVersion: v1
kind: Secret
metadata:
  name: langfuse-redis-secrets
  namespace: default
type: Opaque
data:
  # Base64 encoded values for Redis
  REDIS_HOST: "cmVkaXMtaG9zdC5leGFtcGxlLmNvbQ==" # redis-host.example.com
  REDIS_PORT: "NjM3OQ==" # 6379
  REDIS_USER: "ZGVmYXVsdA==" # default

---
# Helm values demonstrating the use of `secretKeyRef`.
# Save this as values.yaml and use with:
# helm install langfuse ./charts/langfuse -f values.yaml

postgresql:
  # Set `deploy` to false as we are using an external PostgreSQL instance
  deploy: false

  # Use the new `secretKeyRef` to point to the Kubernetes secret
  host:
    secretKeyRef:
      name: langfuse-db-secrets
      key: POSTGRES_HOST
  port:
    secretKeyRef:
      name: langfuse-db-secrets
      key: POSTGRES_PORT

  # The existing password management is unchanged and can be used alongside
  auth:
    existingSecret: "my-postgres-password-secret"
    secretKeys:
      userPasswordKey: "password"
    username:
      secretKeyRef:
        name: langfuse-db-secrets
        key: POSTGRES_USER
    database:
      secretKeyRef:
        name: langfuse-db-secrets
        key: POSTGRES_DB

redis:
  # Set `deploy` to false to use an external Redis
  deploy: false

  host:
    secretKeyRef:
      name: langfuse-redis-secrets
      key: REDIS_HOST
  port:
    secretKeyRef:
      name: langfuse-redis-secrets
      key: REDIS_PORT

  auth:
    existingSecret: "my-redis-password-secret"
    existingSecretPasswordKey: "password"
    username:
      secretKeyRef:
        name: langfuse-redis-secrets
        key: REDIS_USER

# Other configurations remain as needed...
langfuse:
  nextauth:
    url: "https://langfuse.example.com"
    secret:
      # The standard secretKeyRef for other values remains unchanged
      secretKeyRef:
        name: "my-langfuse-app-secrets"
        key: "nextauth-secret"
