# This values.yaml file demonstrates a Langfuse v4 installation that connects to an
# external ClickHouse cluster managed by the ClickHouse Kubernetes Operator.
# All credentials are read from pre-created secrets. Secrets must be set manually or via
# External Secrets Operator like https://external-secrets.io/latest or any other secret management tool.
langfuse:
  image:
    tag: "4" # Pick a current Langfuse v4 release. We recommend pinning a version, e.g. 4.0.0

  encryptionKey:
    secretKeyRef:
      name: langfuse
      key: encryption-key

  salt:
    secretKeyRef:
      name: langfuse
      key: salt

  nextauth:
    secret:
      secretKeyRef:
        name: langfuse
        key: nextauth-secret

postgresql:
  auth:
    existingSecret: langfuse
    secretKeys:
      adminPasswordKey: postgresql-password
      userPasswordKey: postgresql-password

clickhouse:
  deploy: false
  host: langfuse-clickhouse-headless # FQDN: langfuse-clickhouse-headless.langfuse.svc.cluster.local
  auth:
    username: default
    existingSecret: langfuse-clickhouse-auth
    existingSecretKey: password

redis:
  auth:
    existingSecret: langfuse
    existingSecretPasswordKey: redis-password

s3:
  auth:
    existingSecret: langfuse
    rootUserSecretKey: s3-user
    rootPasswordSecretKey: s3-password
