{{- if and .Values.clickhouse.deploy .Values.clickhouse.keeper.enabled -}}
apiVersion: clickhouse.com/v1alpha1
kind: KeeperCluster
metadata:
  name: {{ include "langfuse.fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "langfuse.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.clickhouse.keeper.replicas }}
  dataVolumeClaimSpec:
    accessModes:
      {{- toYaml .Values.clickhouse.keeper.storage.accessModes | nindent 6 }}
    {{- with .Values.clickhouse.keeper.storage.className }}
    storageClassName: {{ . | quote }}
    {{- end }}
    resources:
      requests:
        storage: {{ .Values.clickhouse.keeper.storage.size | quote }}
  containerTemplate:
    image:
      repository: {{ .Values.clickhouse.keeper.image.repository | quote }}
      tag: {{ .Values.clickhouse.keeper.image.tag | quote }}
    {{- with .Values.clickhouse.keeper.resources }}
    resources:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  podTemplate:
    spec:
      {{- with .Values.clickhouse.keeper.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.clickhouse.keeper.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.clickhouse.keeper.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
