{{- if not .Values.postgresql.deploy }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "langfuse.postgresqlSecretName" . }}
  labels:
    {{- include "langfuse.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.postgresql.auth.password | toString | b64enc | quote }}
{{- end }}