{{- if not .Values.postgresql.deploy }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "langfuse.postgresqlSecretName" . }}
  labels:
    {{- include "langfuse.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.postgresql.auth.password | toString | b64enc | quote }}
  {{- if .Values.postgresql.directUrl }}
  postgres-direct-url: {{ .Values.postgresql.directUrl | toString | b64enc | quote }}
  {{- end }}
  {{- if .Values.postgresql.shadowDatabaseUrl }}
  postgres-shadow-database-url: {{ .Values.postgresql.shadowDatabaseUrl | toString | b64enc | quote }}
  {{- end }}
{{- end }}