name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/*/Chart.yaml'
jobs:
  release:
    name: Release Helm Chart
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Update dependencies
        run: helm dependency update charts/langfuse/

      - name: Set Chart Version
        id: chart-version
        run: |
          # Extract chart version from the Chart.yaml
          CHART_DIR=$(find ./charts -name "Chart.yaml" -not -path "*/\.git/*" | head -1 | xargs dirname)
          CHART_NAME=$(yq e '.name' "$CHART_DIR/Chart.yaml")
          CHART_VERSION=$(yq e '.version' "$CHART_DIR/Chart.yaml")
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "chart_dir=$CHART_DIR" >> $GITHUB_OUTPUT
          echo "chart_name=$CHART_NAME" >> $GITHUB_OUTPUT
          echo "chart_version=$CHART_VERSION" >> $GITHUB_OUTPUT
          echo "repo_lower=$REPO_LOWER" >> $GITHUB_OUTPUT
          echo "Chart: $CHART_NAME:$CHART_VERSION in $CHART_DIR"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package Helm Chart
        run: |
          helm package ${{ steps.chart-version.outputs.chart_dir }} --version ${{ steps.chart-version.outputs.chart_version }}

      - name: Push to GitHub Container Registry
        run: |
          helm push ${{ steps.chart-version.outputs.chart_name }}-${{ steps.chart-version.outputs.chart_version }}.tgz oci://ghcr.io/${{ steps.chart-version.outputs.repo_lower }}/charts

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_GENERATE_RELEASE_NOTES: "true"
